version: "3.9"

services:
  climbing-stuff:
    build: .
    container_name: climbing-stuff_app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PRODUCTION_MODE=true
    restart: unless-stopped