name: Run Tests

on: [pull_request]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Install Python dependencies
        run: venv/bin/pip install -r requirements.txt

      - name: Run Python unit tests
        run: venv/bin/python -m unittest discover tests

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install

      - name: Install Playwright browsers
        # Self-hosted runners are expected to have browser dependencies pre-installed.
        # The --with-deps flag is removed to avoid sudo password prompts in CI.
        run: npx playwright install

      - name: Run Playwright tests
        run: |
          source venv/bin/activate
          npx playwright test --reporter=list 